# GitHub Pages configuration
plugins:
  - jekyll-redirect-from

# Custom redirects
redirect_from:
  - /index.html
  - /servicios.html
  - /nosotros.html
  - /perfil-clienta.html
  - /registro.html
  - /salaoscura.html
  - /admin.html
  - /reset-password.html

permalink: pretty